---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cfje/chaos-loris

inputs:
- name: chaos-loris

outputs:
- name: chaos-loris-deploy

run:
  path: chaos-loris/ci/package.sh

